#! /usr/bin/env python
import time

img_version=time.strftime("%Y-%m-%d")
edition=""
device="rock4c-plus" # rpi more will be added soon
arch="aarch64" # aarch64, armv7h
img_name="BredOS-ARM-rock4c-plus-" + img_version
install_dir="arch"
fs="ext4" # ext4 or btrfs
img_type="image" # image (img.xz) or rootfs (tar.gz)
img_backend="loop" # loop or qemu-nbd
# append root=PARTUUID=XXXXXX-02 + CMDLINE will always be added to the kernel command line
# if you use btrfs you need add rootflags=subvol=@ rootfstype=btrfs
cmdline="console=ttyAML0,115200n8 console=ttyS2,1500000n8 console=ttyFIQ0,1500000n8 console=tty1 consoleblank=0 loglevel=0 panic=10 rootwait rw init=/sbin/init rootfstype=ext4 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory swapaccount=1 irqchip.gicv3_pseudo_nmi=0 switolb=1 coherent_pool=2M"
configtxt='''
label BredOS ARM
    kernel /vmlinuz-linux-rockchip-rk3588
    initrd /initramfs-linux-rockchip-rk3588.img
    devicetreedir /dtbs/
'''
